package flagkit

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.clipToBounds
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Shape
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.unit.DpSize
import flagkit.flags.*
import flagkit.flags.AD

internal data class Flag(
    val countryCode: String,
) {
    val originalImage: ImageVector?
        get() = listOf(
            FlagKit.AD,
            FlagKit.AE,
            FlagKit.AF,
            FlagKit.AG,
            FlagKit.AI,
            FlagKit.AL,
            FlagKit.AM,
            FlagKit.AO,
            FlagKit.AR,
            FlagKit.AS,
            FlagKit.AT,
            FlagKit.AU,
            FlagKit.AW,
            FlagKit.AX,
            FlagKit.AZ,
            FlagKit.BA,
            FlagKit.BB,
            FlagKit.BD,
            FlagKit.BE,
            FlagKit.BF,
            FlagKit.BG,
            FlagKit.BH,
            FlagKit.BI,
            FlagKit.BJ,
            FlagKit.BL,
            FlagKit.BM,
            FlagKit.BN,
            FlagKit.BO,
            FlagKit.BR,
            FlagKit.BS,
            FlagKit.BT,
            FlagKit.BW,
            FlagKit.BY,
            FlagKit.BZ,
            FlagKit.CA,
            FlagKit.CD,
            FlagKit.CF,
            FlagKit.CG,
            FlagKit.CH,
            FlagKit.CI,
            FlagKit.CK,
            FlagKit.CL,
            FlagKit.CM,
            FlagKit.CN,
            FlagKit.CO,
            FlagKit.CR,
            FlagKit.CU,
            FlagKit.CV,
            FlagKit.CW,
            FlagKit.CX,
            FlagKit.CY,
            FlagKit.CZ,
            FlagKit.DE,
            FlagKit.DJ,
            FlagKit.DK,
            FlagKit.DM,
            FlagKit.DO,
            FlagKit.DZ,
            FlagKit.EC,
            FlagKit.EE,
            FlagKit.EG,
            FlagKit.ER,
            FlagKit.ES,
            FlagKit.ET,
            FlagKit.EU,
            FlagKit.FI,
            FlagKit.FJ,
            FlagKit.FK,
            FlagKit.FM,
            FlagKit.FO,
            FlagKit.FR,
            FlagKit.GA,
            FlagKit.GB,
            FlagKit.GBENG,
            FlagKit.GBNIR,
            FlagKit.GBSCT,
            FlagKit.GBWLS,
            FlagKit.GBZET,
            FlagKit.GD,
            FlagKit.GE,
            FlagKit.GF,
            FlagKit.GG,
            FlagKit.GH,
            FlagKit.GI,
            FlagKit.GL,
            FlagKit.GM,
            FlagKit.GN,
            FlagKit.GP,
            FlagKit.GQ,
            FlagKit.GR,
            FlagKit.GS,
            FlagKit.GT,
            FlagKit.GU,
            FlagKit.GW,
            FlagKit.GY,
            FlagKit.HK,
            FlagKit.HM,
            FlagKit.HN,
            FlagKit.HR,
            FlagKit.HT,
            FlagKit.HU,
            FlagKit.ID,
            FlagKit.IE,
            FlagKit.IL,
            FlagKit.IM,
            FlagKit.IN,
            FlagKit.IO,
            FlagKit.IQ,
            FlagKit.IR,
            FlagKit.IS,
            FlagKit.IT,
            FlagKit.JE,
            FlagKit.JM,
            FlagKit.JO,
            FlagKit.JP,
            FlagKit.KE,
            FlagKit.KG,
            FlagKit.KH,
            FlagKit.KI,
            FlagKit.KM,
            FlagKit.KN,
            FlagKit.KP,
            FlagKit.KR,
            FlagKit.KW,
            FlagKit.KY,
            FlagKit.KZ,
            FlagKit.LA,
            FlagKit.LB,
            FlagKit.LC,
            FlagKit.LGBT,
            FlagKit.LI,
            FlagKit.LK,
            FlagKit.LR,
            FlagKit.LS,
            FlagKit.LT,
            FlagKit.LU,
            FlagKit.LV,
            FlagKit.LY,
            FlagKit.MA,
            FlagKit.MC,
            FlagKit.MD,
            FlagKit.ME,
            FlagKit.MF,
            FlagKit.MG,
            FlagKit.MH,
            FlagKit.MK,
            FlagKit.ML,
            FlagKit.MM,
            FlagKit.MN,
            FlagKit.MO,
            FlagKit.MP,
            FlagKit.MQ,
            FlagKit.MR,
            FlagKit.MS,
            FlagKit.MT,
            FlagKit.MU,
            FlagKit.MV,
            FlagKit.MW,
            FlagKit.MX,
            FlagKit.MY,
            FlagKit.MZ,
            FlagKit.NA,
            FlagKit.NC,
            FlagKit.NE,
            FlagKit.NF,
            FlagKit.NG,
            FlagKit.NI,
            FlagKit.NL,
            FlagKit.NO,
            FlagKit.NP,
            FlagKit.NR,
            FlagKit.NU,
            FlagKit.NZ,
            FlagKit.OM,
            FlagKit.PA,
            FlagKit.PE,
            FlagKit.PF,
            FlagKit.PG,
            FlagKit.PH,
            FlagKit.PK,
            FlagKit.PL,
            FlagKit.PM,
            FlagKit.PN,
            FlagKit.PR,
            FlagKit.PS,
            FlagKit.PT,
            FlagKit.PW,
            FlagKit.PY,
            FlagKit.QA,
            FlagKit.RE,
            FlagKit.RO,
            FlagKit.RS,
            FlagKit.RU,
            FlagKit.RW,
            FlagKit.SA,
            FlagKit.SB,
            FlagKit.SC,
            FlagKit.SD,
            FlagKit.SE,
            FlagKit.SG,
            FlagKit.SH,
            FlagKit.SI,
            FlagKit.SJ,
            FlagKit.SK,
            FlagKit.SL,
            FlagKit.SM,
            FlagKit.SN,
            FlagKit.SO,
            FlagKit.SR,
            FlagKit.SS,
            FlagKit.ST,
            FlagKit.SV,
            FlagKit.SX,
            FlagKit.SY,
            FlagKit.SZ,
            FlagKit.TC,
            FlagKit.TD,
            FlagKit.TF,
            FlagKit.TG,
            FlagKit.TH,
            FlagKit.TJ,
            FlagKit.TK,
            FlagKit.TL,
            FlagKit.TM,
            FlagKit.TN,
            FlagKit.TO,
            FlagKit.TR,
            FlagKit.TT,
            FlagKit.TV,
            FlagKit.TW,
            FlagKit.TZ,
            FlagKit.UA,
            FlagKit.UG,
            FlagKit.UM,
            FlagKit.US,
            FlagKit.USCA,
            FlagKit.UY,
            FlagKit.UZ,
            FlagKit.VA,
            FlagKit.VC,
            FlagKit.VE,
            FlagKit.VG,
            FlagKit.VI,
            FlagKit.VN,
            FlagKit.VU,
            FlagKit.WF,
            FlagKit.WS,
            FlagKit.XK,
            FlagKit.YE,
            FlagKit.YT,
            FlagKit.ZA,
            FlagKit.ZM,
            FlagKit.ZW,
        ).find {
            it.name == countryCode.uppercase()
        }

    val regionName: String?
        get() = getISOCountries().find { it.uppercase() == countryCode }
}

@Composable
fun Flag(
    countryCode: String,
    shape: Shape,
    size: DpSize,
    modifier: Modifier = Modifier,
    contentScale: ContentScale = ContentScale.FillWidth,
    placeholder: @Composable () -> Unit = {
        FlagPlaceholder(modifier = modifier, shape = shape, size = size)
    },
) {
    val flag = Flag(countryCode)
    flag.originalImage?.let { image ->
        Image(
            modifier = modifier
                .size(size)
                .clip(shape),
            imageVector = image,
            contentDescription = listOfNotNull("Flag", flag.regionName).joinToString(" "),
            contentScale = contentScale,
        )
    } ?: placeholder()
}
